### ISSUE TITLE
No instance variables in partials

### ISSUE THREAD

**Issue by mockdeep** [brigade/haml-lint#121]
One rule of thumb that would be nice to apply is to not allow instance variables in partials. Not sure if it would make sense to have it on my default, though.

**Comment by sds** [comment]
Hey @mockdeep,

How would you detect a partial, in this case? Different companies may have different naming conventions to identify a partial versus a regular template.

**Comment by mockdeep** [comment]
@sds I've actually only seen the convention of naming partials beginning with `_`. What other conventions are there that you know of? If they are based on file naming, it might make sense to make it configurable based on a regex.

**Comment by sds** [comment]
To be fair I haven't actually seen otherwise, but my experience is that there are always teams out there who come up with different naming schemes. For example, perhaps a team prefers to have the explicit word `_partial` at the end of the file name to mark it as such.

In any case, this sounds reasonable as long as you can define a regex for identifying a file as a partial.

**Comment by shepmaster** [comment]
I'm also a fan of not allowing *any* instance variables in *any* view (preferring helper methods instead). That might be an easier thing to implement to get started. The regex for "files to include" and "files to exclude" could be refinements on that.

**Comment by mockdeep** [comment]
Awesome, thanks @michaelherold!
