### ISSUE TITLE
Remove haml-lint from rubygems (!?), mark 0.17.1 as latest release on Github.

### ISSUE THREAD

**Issue by paulkogel** [brigade/haml-lint#131]
having `haml-lint` and `haml_lint` on Rubygems is very confusing, especially because this Github repository uses the old gem name with a hyphen. First wanted to file an issue to update the version on rubygems...
You probably decided to keep the hyphen-version to support existing apps!? Feel free to close this issue if you've had a discussion about this before. I'd vote for removing `haml-lint` from Rubygems. I simply didn't notice the migration note and had a bad first impression from your gem because `haml-lint` (stuck at version 0.13) still has this issue: https://github.com/brigade/haml-lint/issues/108.

Furthermore, the latest release on the Github [releases page](https://github.com/brigade/haml-lint/releases) is  0.16.0 while there is a tag for version 0.17.1.

**Comment by sds** [comment]
Hey @paulkogel, thanks for noticing the discrepancy with the releases. I've gone ahead and updated the releases page accordingly.

Regarding the name of the gem: yes, I understand this is confusing. To yank the gem is not the responsible thing to do, however, since then anyone can publish to it and effectively hijack a number of people's codebases, getting them to download and run potentially malicious software (since so many still depend on the `haml-lint` gem).

However, perhaps the answer here is to do what Bundler did with the [`bundle`](https://rubygems.org/gems/bundle) gem and just have it depend on the `bundler` gem. I've gone ahead and done that.

**Comment by paulkogel** [comment]
good idea. alternative might have been to update `haml-lint` to the latest version and copublish each future release!?
anyway, thank you for explaining. let's hope others aren't as easily confused in the future.
