### ISSUE TITLE
Add auto-fix option

### ISSUE THREAD

**Issue by shepmaster** [brigade/haml-lint#140]
I'm certain this wouldn't be trivial, but would be *greatly* appreciated for projects adding haml-lint later in their lifecycles.

**Comment by sds** [comment]
Thanks for suggesting ways to improve the tool, @shepmaster.

Indeed, this is fair from trivial. For all practical purposes this cannot be done because of how we extract the Ruby code from the HAML template. In a nutshell, HAML code like this:

```haml
- unused_variable = 42
- if some_method
  %p Goodbye
- else
  %p Hello
```

...gets turned into something like this:

```ruby
unused_variable = 42
if some_method
  puts ...
else
  puts ...
end
```

Thus any corrections made by RuboCop's `--auto-correct` flag would then have to somehow be converted back into the original HAML document.

I hope it's clear that the mapping as it currently stands is one-way, so re-mapping changes back into the originally document is largely impractical. Having said that, there may be a scheme where a two-way mapping could be created to support this, but unless someone from the community steps up to suggest one, this simply won't happen.

Furthermore, even if you cross that hurdle, supporting parse tree editing of HAML documents themselves would need to be added. This is another challenge where we might be able to get somewhere, but it's a significant hurdle.

Thus while I'm definitely not against the idea (would love to have it), the work involved is so substantial that unless a well-tested pull request adds this functionality you won't be seeing it any time soon.

Hope that explains things!

**Comment by sam0x17** [comment]
Yeah this is a deal breaker for me -- if there was an auto / fix feature I would use this in my CI
