### ISSUE TITLE
Bundle the haml library in the gem rather than depending on it

### ISSUE THREAD

**Issue by connorshea** [brigade/haml-lint#150]
At GitLab we use [hamlit](https://github.com/k0kubun/hamlit) for rendering haml views rather than using haml directly. The gem is a more performant implementation, and we saw something like ~250-300ms difference when using Hamlit.

Recently brakeman switched from depending on haml (and other libraries) to [bundling/embedding it in their library](https://github.com/presidentbeef/brakeman/pull/845). This is preferable for a few reasons, mainly to avoid any methods being overridden by Haml and to prevent dependency conflicts.

Would it be possible to embed haml into haml-lint rather than relying on it as a dependency? That's the main thing blocking us from using the gem right now.

Thanks,
Connor Shea

**Comment by sds** [comment]
Hey @connorshea, thanks for bringing this issue to light.

I'm open to this, but vendoring seems rather clumsy (unless I'm misunderstanding the approach here).

If you vendor the gem, you still end up loading modules under the `Haml` namespace, so it's not clear how you avoid "methods being overridden by Haml", since the code is still loaded and thus any monkey patches still applied.

I do see how this solves the dependency conflicts, since `hamlit` depends on the beta version of the `haml` gem (currently [`4.1.0.beta.1`](https://github.com/k0kubun/hamlit/blob/1fa594f14eaf1c5953ebb9743b463a43115c5512/hamlit.gemspec#L31) at time of writing). So vendoring does help us avoid this case.

At the end of the day, vendoring isn't great, so I'd like some more justification here before we jump head first into this.

Can you elaborate on the method overriding justification a bit to help me understand?

**Comment by sds** [comment]
Also, FWIW it looks like the reason `hamlit` specifies a dependency on `haml` 4.1.0.beta.1 is to _require_ any tools to be compatible with that specific version. 

This is an interesting decision, so it may be worthwhile to understand why that project opted to impose this requirement.

**Comment by connorshea** [comment]
I must be wrong then, it's probably fine not to bundle it in that case. After some more thought I think this is a non-issue, my apologies :)
