### ISSUE TITLE
How to use haml-lint as a checker in my rpsec or with rubocop

### ISSUE THREAD

**Issue by divyanshumehta** [brigade/haml-lint#199]
I my using Rspec to test my app. The Rspec runs RuboCop by default and the test that I wrote. I want to run `haml-lint` on all my views in Rspec. Is there a way to do it. I want to get the haml linting errors in my tests.

OR

I have been working on my Rails app and I am using HAML for templating. RuboCop takes care of linting my .rb files. Currently I have to run `haml-lint <file path>` to check my .haml files. Is there a way to do this through Rubocop.

PS: I want `haml-lint` to run by deafult when I run Rspec to test my app. Either it can be directly added to Rspec or added to RuboCop which is also called in my Rspec.

Thanks in advance. Really need this.

**Comment by michaelherold** [comment]
It sounds like you might be a newcomer to Ruby. If so, welcome to the community!

Running haml-lint as part of RSpec doesn't make sense because RSpec is both for and written in Ruby code, not Haml code. Instead, you can set up a Rake task that is part of your default task.

This looks like (in `Rakefile`):

```ruby
require "haml_lint/rake_task"
require "rspec/core/rake_task"
require "rubocop/rake_task"

HamlLint::RakeTask.new(:haml_lint)
RuboCop::RakeTask.new(:rubocop)
RSpec::RakeTask.new(:spec)

task default: %i(rubocop haml_lint spec)
```

You'd then use this Rake task by running `rake`, since it is is part of the default task. If you wanted to only run Haml-Lint, you could run `rake haml_lint`. (You might be using bundler, which means you would do `bundle exec rake` instead of plain `rake`).

See [this part of the readme](https://github.com/brigade/haml-lint#rake-integration) for more information.

**Comment by divyanshumehta** [comment]
So if I run `bundle exec rspec` which starts testing my app will it also have the outputs of `haml-lint`?

**Comment by michaelherold** [comment]
No. There is no way to tie `haml_lint` to the running of RSpec. You have to use a Rake task or the command line tool.

If you follow the instructions above, you can run `bundle exec rake` and it will run `haml-lint`, `rubocop`, and `rspec`.

**Comment by divyanshumehta** [comment]
Thanks @michaelherold I got what i needed thank you so much. I think you the issue can be closed.

**Comment by michaelherold** [comment]
I'm glad you were able to figure it out!
