### ISSUE TITLE
How can I do underlining errors as rubocop?

### ISSUE THREAD

**Issue by onii4an** [brigade/haml-lint#274]
![image](https://user-images.githubusercontent.com/32365944/43125078-af704018-8f31-11e8-86cd-a63267471d3f.png)
Higher is haml-lint
Lower is rubocop
![image](https://user-images.githubusercontent.com/32365944/43125122-c8dd5248-8f31-11e8-9039-9f4b3cd4f6a4.png)

**Comment by sds** [comment]
Hey @onii4an, this is difficult to do with HAML-Lint. Since we generate Ruby code from HAML templates when running RuboCop against them, there isn't a perfect 1:1 mapping of the original HAML code to the resulting Ruby code processed by RuboCop.

If you're referring to underline support in general, there are quirks of the HAML-Lint parse tree that make it difficult to know the exact line/column of a node in the tree.

Happy to accept a pull request that solves this challenge, but it's a hard one and we won't be pursuing a solution ourselves.
