### ISSUE TITLE
Add inherit_from as for rubocop.yml

### ISSUE THREAD

**Issue by Jerskouille** [brigade/haml-lint#72]
Hi,

First, thanks a lot for this linter. It works flawlessly !
I have a feature request :
It would be really great to be able to configure *haml-lint* the same way *rubocop* does with `inherit_from`.
This would allow to have global overrides in `~/.haml-lint.yml` and your local project overrides in `./haml-lint.yml`.

Hope you will consider this !

Cheers !

**Comment by sds** [comment]
Hey @Jerskouille,

Glad to hear `haml-lint` has been serving you well. I've actually thought about implementing your request, but when I tried to add support for the idea to Rubocop in https://github.com/bbatsov/rubocop/pull/583, it was pointed out to me that this isn't really a good idea. Allow me to explain.

I believe your intention with adding support to `inherit_from` `~/.haml-lint.yml` is so you can DRY up your configurations so you aren't repeating the same configuration for all your repositories. However, if you think about it, the repository is the singular unit of composition&mdash;any configuration should never reference a file outside the repository, as that makes it inherently brittle. What happens if someone clones your repository and doesn't have the file in question?

For this reason, `haml-lint` was designed to only have a single file for configuration, located in the root of the repository. This way regardless of who clones your repository they will always have the intended configuration, with no additional work required on their part.

Hope that explains things. Keep sending us ways we can improve the tool!
