### ISSUE TITLE
How to un-ignore the ignored rubocop cops?

### ISSUE THREAD

**Issue by maxjacobson** [brigade/haml-lint#77]
haml-lint ignores some rubocop cops (https://github.com/brigade/haml-lint/blob/master/config/default.yml#L56-L70)

Let's say I didn't want it to...

I tried figuring out how to configure haml-lint to enable those cops but couldn't quite figure it out. Is it possible?

Thanks!

**Comment by sds** [comment]
Hey @maxjacobson,

Those cops are ignored for a good reason: `haml-lint` takes some shortcuts when extracting Ruby code from a HAML template, which necessarily results in noise from those cops.

Can you give a specific example of a copy you want to disable?

If you still REALLY want to do this, you just need to redefine the entire list in your local `.haml-lint.yml`:

```yaml
linters:
  RuboCop:
    ignored_cops: [] # NOT RECOMMENDED!
```

**Comment by maxjacobson** [comment]
Hey @sds thanks for getting back to me!

there are a few nitpicky things I was hoping haml-lint would catch:

* [the newline character at end of file](https://robots.thoughtbot.com/no-newline-at-end-of-file) thing
* tabs instead of spaces for indentation
* 4 spaces instead of 2 spaces for indentation

are you saying it doesn't analyze the file as it is, but first transforms it into some other ruby file, so it wouldn't catch those things necessarily anyway?

thanks!

**Comment by sds** [comment]
Yes, as part of its preprocessing, `haml-lint` will convert HAML like this:

```haml
- if signed_in?(viewer)
  %span Stuff
  = link_to 'Sign Out', sign_out_path
- else
  .some-class{ class: my_method }= my_method
  = link_to 'Sign In', sign_in_path
```
...into Ruby like this:
```ruby
if signed_in?(viewer)
  link_to 'Sign Out', sign_out_path
else
  { class: my_method }
  my_method
  link_to 'Sign In', sign_in_path
end
```

Notice that the Ruby is somewhat nonsensical. All `haml-lint` tries to do is preserve the ordering of declarations and uses of variables, as well as the order Ruby that code appears in the template. This means you probably won't have a translation that makes perfect sense.

For things like indentation, it may be possible to munge things into shape but I haven't looked too deeply into that. Right now if you have HAML like the following:

```haml
%tag{ some: 'hash', 
      attributes: 'here' }
```

...it will get extracted as:

```ruby
{ some: 'hash', attributes: 'here' }
```

...losing some of the whitespace in the process. This makes it difficult to have it generate correct indentation.

For your request about final newlines, I think it's reasonable for `haml-lint` to support that first hand via a `FinalNewline` linter, since RuboCop won't have any idea whether your HAML template ends with a newline or not.

**Comment by maxjacobson** [comment]
Makes total sense, thanks for explaining.

Adding a newline check would be super helpful! What do you think about checking for the presence of a tab character? I think most Rubyists are using spaces, not tabs, so checking for the presence of a tab file in the source haml file might be useful as well :smile:

**Comment by sds** [comment]
Added a final newline check in 1635c078c2. Enforcing spaces instead of tabs in indentation was added in  #81.

**Comment by maxjacobson** [comment]
Awesome! Thanks a lot @sds
